// src/widgets/dual-tag.jsx
import React from "react";

export default function DualTag(props) {
  let title = props.title;
  let value = props.value;
  return (
    <div className="flex flex-col md:flex-row">
      <span className="bg-sky-200 px-2 py-1 text-gray-700 dark:bg-gray-700 dark:text-gray-100">
        {title}
      </span>
      <span className="bg-gray-800 px-2 py-1 text-gray-400 dark:bg-white dark:text-gray-700">
        {value}
      </span>
    </div>
  );
}

// src/lib/components/dual-tag.svelte
<script>
  export let value;
  export let title;
</script>

<div class="flex flex-col md:flex-row">
  <span
    class="bg-sky-200 px-2 py-1 text-center text-gray-700 dark:bg-gray-700 dark:text-gray-100"
  >
    {title}
  </span>
  <span
    class="bg-gray-700 px-2 py-1 text-center text-gray-200 dark:bg-white dark:text-gray-700"
  >
    {value}
  </span>
</div>
