// src/widgets/mini-showcase.jsx
"use client";
import React, { useState } from "react";
import dynamic from "next/dynamic";
import { GiCubes, GiSeaDragon } from "react-icons/gi";
import { RiSwordFill } from "react-icons/ri";

const RubikScene = dynamic(() => import("scenes/rubik"));
const DragonScene = dynamic(() => import("scenes/dragon"));
const SaborScene = dynamic(() => import("scenes/sabor"));
//const SpiderScene = dynamic(() => import('scenes/spider'))

function CanvasContainer(props) {
  return (
    <div
      className="flex aspect-square w-full flex-col-reverse
        items-center justify-start
        md:aspect-video
        md:grow
        md:flex-row-reverse"
    >
      {props.children}
    </div>
  );
}

function HistoryNavigator(props) {
  return (
    <div
      className="flex w-full justify-center
        md:w-auto md:flex-col"
    >
      {props.children}
    </div>
  );
}

function HistoryButton(props) {
  return (
    <button
      className="p-4 aria-checked:bg-gray-700 aria-checked:text-white dark:aria-checked:bg-gray-300 dark:aria-checked:text-gray-800"
      onClick={props.onClick}
      aria-checked={props.active ? "true" : undefined}
    >
      {props.children}
    </button>
  );
}

export default function MiniShowcase() {
  let [activeSet, setActiveSet] = useState(0);
  return (
    <CanvasContainer>
      <HistoryNavigator>
        <HistoryButton onClick={() => setActiveSet(0)} active={activeSet === 0}>
          <GiCubes size="1.5em" />
        </HistoryButton>
        <HistoryButton onClick={() => setActiveSet(1)} active={activeSet === 1}>
          <GiSeaDragon size="1.5em" />
        </HistoryButton>
        <HistoryButton onClick={() => setActiveSet(2)} active={activeSet === 2}>
          <RiSwordFill size="1.5em" />
        </HistoryButton>
      </HistoryNavigator>
      {(() => {
        switch (activeSet) {
          case 0:
            return <RubikScene />;
          case 1:
            return <DragonScene />;
          case 2:
            return <SaborScene />;
          //   case 3:
          //     return <SpiderScene />
          default:
            return <RubikScene />;
        }
      })()}
    </CanvasContainer>
  );
}

// src/lib/components/mini-showcase.svelte
<script>
  import RubikIcon from "~icons/arcticons/cubesolver";
  import DragonIcon from "~icons/game-icons/sea-dragon";
  import SwordIcon from "~icons/ri/sword-fill";
  import MagicIcon  from '~icons/fa-solid/hand-sparkles'

  let selected = 0;
  let sceneInstance;
  let Scene;
  function performMagic() {
    sceneInstance.performMagic();
  }
  async function select(value) {
    selected = value;
    switch (selected) {
      case 0:
        Scene = (await import("$lib/components/rubik.svelte")).default;
        break;
      case 1:
        Scene = (await import("$lib/components/dragon.svelte")).default;
        break;
      case 2:
        Scene = (await import("$lib/components/sabor.svelte")).default;
        break;
    }
  }
  select(0);
</script>

<div
  class="flex aspect-square w-full flex-col-reverse
        items-center justify-start
        md:aspect-video
        md:grow
        md:flex-row-reverse"
>
  <div
    class="flex gap-2 w-full justify-center
        text-2xl md:w-auto md:flex-col"
  >
    <button
      class="p-4 rounded-full bg-sky-600/20 dark:text-white text-gray-800"
      on:click={performMagic}
    >
      <MagicIcon class="animate-waving-hand" />
    </button>
    <button
      class="p-4 aria-checked:bg-gray-700 aria-checked:text-white dark:aria-checked:bg-gray-300 dark:aria-checked:text-gray-800"
      aria-checked={selected == 0}
      on:click={() => select(0)}
    >
      <RubikIcon />
    </button>
    <button
      class="p-4 aria-checked:bg-gray-700 aria-checked:text-white dark:aria-checked:bg-gray-300 dark:aria-checked:text-gray-800"
      aria-checked={selected == 1}
      on:click={() => select(1)}
    >
      <DragonIcon />
    </button>
    <button
      class="p-4 aria-checked:bg-gray-700 aria-checked:text-white dark:aria-checked:bg-gray-300 dark:aria-checked:text-gray-800"
      aria-checked={selected == 2}
      on:click={() => select(2)}
    >
      <SwordIcon />
    </button>
  </div>
  <svelte:component bind:this={sceneInstance} this={Scene} />
</div>
